name = "ferhathamza"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Bind the D1 Database
[[d1_databases]]
binding = "DB" 
database_name = "ferhathamza-db"
database_id = "YOUR_DATABASE_ID_FROM_CLOUDFLARE_DASHBOARD"

# Define the variable for your password (set value in dashboard)
[vars]
ADMIN_SECRET = "Hamza2026"
